server:
  port: 8080

schedule:
  cron: 0 0 0 * * *

providers:
  - name: FXDS
    url: https://fxds-public-exchange-rates-api.oanda.com/cc-api/currencies
    parameters:
      base: EUR
      quote: USD
      start_date: 2025-01-01
      end_date: 2025-01-01
      data_type: chart